language: node_js
node_js:
- stable
before_script:
- npm run clear-guides
- npm run convert-markdown -- --all
deploy:
  provider: pages
  skip_cleanup: true
  file: guides/*
  local_dir: guides
  target_branch: gh-pages
  on:
    all_branches: true
    repo: Bucko13/bcoin-org.github.io
    tags: true